version = 1

test_patterns = [
  "Data Structures/test_*.py"
]

exclude_patters = [
  "Data
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true