language: python
python:
  - "3.7.5"

before_install:
  - cat codecov.yml | curl --data-binary @- https://codecov.io/validate
  - pip install -U pip

install:
  - pip install -r requirements.txt
  
script:
  - chmod +x ./
  - pytest --cov=./ --cov-report=xml

after_success:
  - curl https://deepsource.io/cli | sh
  - bash <(curl -s https://codecov.io/bash)
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml