language: python
python:
  - "3.7.5"

before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov
  - pip install -U sentry-sdk==0.14.1
  
script:
  - pytest --cov=stack

after:
  - bash <(curl -s https://codecov.io/bash)