language: python
python:
  - "3.7.5"

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  
script:
  - pytest --cov=stack --verbose

after_success:
  - coverage xml
  - curl https://deepsource.io/cli | sh
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
  - bash <(curl -s https://codecov.io/bash)